eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8099
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /produce1/**
      serviceId: spring-cloud-client-producer1
    api-b:
      path: /client/**
      serviceId: eureka-client
